### PR TITLE
Add config example to SKR 1.4 with bltouch and TMC 2208

### PR DESCRIPTION
**Pull request by pacocatech**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

This modification includes a base to apply the marlin on bigtreetech SKR 1.4 boards, all the adjustments were made to be executed and are running correctly.
In addition we have already enabled BLTOUCH and also TMC 2208 drivers.

### Benefits

Inclusion of configuration for BigTreeTech SRK 1.4 boards.
We also have the configuration of the BLTOUCH function and TMC2208 drivers.

### Related Issues

The idea is to make it easier for people who have SKR 1.4 boards, as we currently do not have this configuration guide and the BigTreeTech repository does not keep this configuration up to date.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Can you add a readme outlining exactly which hardware this covers and what mods need to be made to stock hardware to get it working?

**Comment by pacocatech** [comment]
@thisiskeithb done!

**Comment by ellensp** [comment]
NOZZLE_TO_PROBE_OFFSET is dependant on the mount you use, and no mention of the mount is given.

**Comment by pacocatech** [comment]
Todo mundo cria versões de configurações e ninguém faz esse tipo de menção, eu posso adicionar essa nota sem nenhum problema.

**Comment by pacocatech** [comment]
@ellensp Everyone creates versions of configurations and nobody makes that kind of mention, I can add this note without any problem.

**Pull request closed without merging**
