### PR TITLE
CR-10 Mini - BigTreeTech SKR Mini E3 2.0

### PR DESCRIPTION
**Pull request by Skiddz**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Configuration files for Marlin 2.0.7.2 on a CR-10 Mini with a BigTreeTech SKR Mini V2.0 board with the stock hot-end and screen.  
Stock CR-10 screen is enabled
AUTO_BED_LEVELING_BILINEAR is enabled
BLTouch is enabled, 
 - probe offsets are for a Bullseye duct w/left hand probe mount. 
 - 5x5 probe grid with 2 probes per point 
 - Z-Min is configured to use the Z-Probe port.  
 - Probe is used for Z-Homing
 - Leveling after homing is disabled.
 LINEAR_ADVANCE is enabled.
 ARC_SUPPORT is enabled.

### Benefits

Provides configuration files for Creality CR-10 Mini 3D printers upgraded with BigTreeTech SKR E3 Mini V2.0 boards.

### Related Issues

None

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Can you add a readme with a list of mods to accompany the config?

Without one, it ends up creating a lot of issues when users upgrade not know what extra hardware or addons are needed.

Having said that, it’d be better to revert as much as possible to match the stock hardware (other than the motherboard) so this config is more universal.

**Review by 09306677806 — COMMENTED** [review]
Ok, I just want my previous account to enter this new line so I can exchange

**Review by 09306677806 — COMMENTED** [review]
If possible, Marlin, okay. I don't realize it much. It wasn't my first hand. I just gave it to Finti.

**Review by 09306677806 — APPROVED** [review]
If possible, Marlin, okay. I don't realize it much. It wasn't my first hand. I just gave it to Finti.

**Pull request merged**
