### PR TITLE
repack private jpegs with jpeg.io

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Image data in private data directory is two large to fit into DACAI  e3v2 lcd clone (F1C100s mpu)

Repacked all jpeg data with jpeg.io online tool. They now fit.

### Benefits

Fit into DACAI e3v2 lcd clone flash memmory.

### Related Issues
https://github.com/MarlinFirmware/Configurations/issues/805

### CODE REVIEW

**Comment by thinkyhead** [comment]
Some of these might look better if they were compressed from an original clean image. I can provide those.

**Comment by ellensp** [comment]
I could not see any visible difference...

**Comment by Sparticuz** [comment]
@ellensp I'm assuming this is in release-2.1.2, but I received this trying to flash.
image

**Comment by Sparticuz** [comment]
It looks like because I used an iPad and it created a ton of . (dot) files.

**Pull request merged**
