### PR TITLE
Added HICTOP 3DP-17

### PR DESCRIPTION
**Pull request by Gadgeteering**
### Description

Add configuration files for HICTOP 3DP-17 printer

### CODE REVIEW

**Comment by Gadgeteering** [comment]
Built and tested on my HICTOP 3DP-17

**Comment by thinkyhead** [comment]
Thanks for the submission! New configurations must be based on the default configurations from `import-2.1.x` for inclusion in the next release. The configurations in this PR are targeted to an older version of Marlin, so they will need to be updated to the current version, `02010300 `.

**Comment by thinkyhead** [comment]
I went ahead and applied the needed updates. Please check to make sure they still work as intended and have all the same changes. One quick way to see all the changes in isolation is to replace the Hictop configs with the default configs, then use GitHub Desktop to view the differences.

**Comment by Gadgeteering** [comment]
line 1601 should read 

```c++
#define NOZZLE_TO_PROBE_OFFSET { 10, 50, -1} 
```

I have tried to build the firmware but get error for the code between lines 3212->3215

```c++
//#define DGUS_LCD_UI ORIGIN
#if DGUS_UI_IS(MKS)
  #define USE_MKS_GREEN_UI
#elif DGUS_UI_IS(IA_CREALITY)
``` 

I am using PlaformIO in visual studio code to build the firmware

**Comment by thisiskeithb** [comment]
> I have tried to build the firmware but get error for the code between lines 3212->3215

What's the error? Make sure you're using the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip).

All changed configs in a PR are built and this PR passed:

image

**Comment by Gadgeteering** [comment]
Thanks for your advice, build and tested on my 3D printer

**Comment by thisiskeithb** [comment]
> Thanks for your advice, build and tested on my 3D printer

I assume you closed this PR on accident, so I’ve reopened it.

How’d testing go?

**Comment by Gadgeteering** [comment]
Tested and works

**Comment by Emma2109** [comment]
I seen someone comment PlaformIO studio. I'm trying to figure out how to use the system.
Screenshot_20240920-175549

**Comment by Emma2109** [comment]
Okay thanks 👍

**Comment by Emma2109** [comment]
I did that thank you

**Comment by Emma2109** [comment]
Sorry it's been a very long time since I was able to get back I kind of forgot and just never got back on but I'm back now and I did do those two configures I went back and I looked and they were already configured.

**Pull request merged**
