### PR TITLE
Example configuration files for stock CR-10 with BigTreeTech SKR Mini E3 2.0

### LINKED ISSUE #141: [REQUEST] Creality CR-10 and CR-10S config example for BigTreeTech SKR Mini E3 2.0
Request Creality CR-10 and CR-10S config example files for the new/updated BigTreeTech SKR Mini E3 V2.0 mainboard hardware.

https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3

Biqu and BigTreeTech Store is marketing the SKR Mini E3 2.0 as also compatible with CR-10 (as well as with CR-10S?) as seen in:

https://www.biqu.equipment/products/bigtreetech-skr-mini-e3-v2-0-32-bit-control-board-integrated-tmc2209-uart-for-ender-3

https://www.aliexpress.com/item/4001050145015.html

But they do not include config files and is instead pointing to this (official) upstream MarlinFirmware Configurations repo and that only BigTreeTech SKR Mini E3 2.0 contains config examples for the Ender 3:

https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V2.0/Marlin-2.0.x-SKR-mini-E3-V2.0/config

I see that @thinkyhead already committed Ender 3 config examples for BigTreeTech SKR Mini E3 2.0 however there are currently no configuration example files for CR-10 or CR-10S (or config examples for any other 3D-printers in the CR-10 'older' series):

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%202.0

PS: We are also missing config examples for Ender 5 series which should also be hardware compatible though not marketed so.

### PR DESCRIPTION
**Pull request by Gamester17**
Create example configuration files for stock CR-10 with BigTreeTech SKR Mini E3 2.0 (I also create a separate PR for CR-10S).

### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Example configuration files for stock CR-10 with BigTreeTech SKR Mini E3 2.0 board, (and I also create a separate PR for CR-10S).

Please note that similar examples for BigTreeTech SKR Mini E3 2.0 board are available for Ender-3, Ender-3 Pro, and Ender-5:

* https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3
* https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-5
* https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20Pro

BigTreeTech SKR Mini E3 2.x boards are just as 100% compatible with CR-10 and CR-10S as with Ender-3, Ender-3 Pro, and Ender-5.

I believe also Ender 5 Pro should work with BigTreeTech SKR Mini E3 2.0 without modification, but not sure about Ender 5 Plus.

### Benefits

Example files make it less intimidating for beginners who own a stock CR-10 to upgrade to a BigTreeTech SKR Mini E3 2.0 board.

### Related Issues

PRs #237 + #238 hopefully resolve https://github.com/MarlinFirmware/Configurations/issues/141 which request Creality CR-10 and CR-10S config example for BigTreeTech SKR Mini E3 2.0

In addition, CR-10 and CR-10S config example files for SKR Mini E3 V2.0 has also indirectly been requested by BTT/Biqu community via feature requests for firmware in https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/309 and https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/295

### CODE REVIEW

**Comment by Gamester17** [comment]
FYI, the configuration files are initially based on Ender-3 example files for BTT SKR Mini 2.0 from the import-2.0.x (2.0.7) branch:

- https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%202.0

The configuration has been changed from that and default to configure the following in order for everything required to work:

* Board Type
* Printer Size
* TMC 2209 Drivers
* Axis Direction
* Type 1 Thermocouple for bed and hot end
* Steps/mm
* Acceleration
* Jerk
* petG Preheat Constants added
* Nylon Preheat Constants added
* CR-10 Boot Screen
* CR-10 Status Screen

These example config files are for the stock hardware as they are shipped from Creality factory. There are not pre-configured for Filament Sensor (FIL_RUNOUT), NeoPixel LED, BLTouch, or Linear Advance (LIN_ADVANCE), nor for any other hardware modifications.

Most credit goes to @themodfatherinc who I borrowed much of this configuration optimization from, you can find his repo at:

- https://github.com/themodfatherinc/Marlin/

Some credit also goes to @bigtreetech and @chzj333 for having config files for Ender 3 + 5 series (but no CR-10/CR-10S yet):

- https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V2.0/Marlin-2.0.x-SKR-mini-E3-V2.0/Marlin

Additional inspiration credit also goes to @MickyKom @samgozman @Techknowdude @idjmic and @MakerCorn who shared BTT SKR Mini E3 V1.x config files for CR10, CR10S and CR-10S5 (CR-10S5/ CR-10 S5 CR-10S 5):

- https://github.com/MickyKom/SKR-Mini-E3-CR-10s

- https://github.com/samgozman/CR-10-BIGTREETECH-SKR-mini-E3/tree/master/firmware/V1.2/Marlin-2.0.x-SKR-Mini-E3-V1.2/Marlin

- https://github.com/Techknowdude/Marlin-CrealityPrusa-SKRMiniE3

- https://github.com/idjmic/Marlin-2.0.x-07-30-2020-bug-fix

- https://github.com/MakerCorn/Marlin-2.x-SKR-Mini-CR10S-S5-Firmware

**Comment by Gamester17** [comment]
@thisiskeithb Can you please tell me if this patch with example config files should have done `bugfix-2.0.x` branch instead?

If so then wondering why you do not set `bugfix-2.0.x` as the "default" branch on GitHub to use it as master as standard?

PS: There are no instructions in the README.md file of this specific branch that let people know not to PR to the default branch.

**Comment by Gamester17** [comment]
@thisiskeithb Can you please tell me if this patch with example config files should have done `bugfix-2.0.x` branch instead?

If so then wondering why you do not set `bugfix-2.0.x` as the "default" branch on GitHub to use it as master as standard?

**Comment by Gamester17** [comment]
I know this PR is closed but FYI, @Marlor posted a little late after it was merged commenting that he thinks that config is wrong: 

> This config looks wrong.
> 
> Some changes are personal preferences, which should stay the same as the default config.
> like the edits to `ADVANCED_PAUSE`, `PID` or preheat presets.
> 
> Some things should not be changed because the rest of the printer hardware stays the same.
> like `STEPS_PER_UNIT`,`X/Y_CURRENT` or Acceleration/jerk
> 
> Some advanced functions which should not be in an example
> `S_CURVE_ACCELERATION` and `LIN_ADVANCE` at the same time can easily drive a beginner crazy
> 
> or dangerous, like the change of max temp from 250 to 275 on the standard ptfe lined hotend

I replied that since already merged and hence that pulls request has already been closed and thus no changes can be done there now, so the best way forward from now on would be if make an edit and submit any changes as a pull request yourselves, see:

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/CR-10S/BigTreeTech%20SKR%20Mini%20E3%202.0

Maybe also take an extra look at CrealityV1 stock board too?

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/CR-10S/CrealityV1

Same goes for CR-10 which is based on the same config https://github.com/MarlinFirmware/Configurations/pull/237

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/CR-10/BigTreeTech%20SKR%20Mini%20E3%202.0

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/CR-10/CrealityV1

**Comment by Velo555** [comment]
Is there going to be a example config for the CR-10 for SKR Mini E3 v3??

**Comment by thisiskeithb** [comment]
> Is there going to be a example config for the CR-10 for SKR Mini E3 v3??

@Velo555 This has already been requested https://github.com/MarlinFirmware/Configurations/issues/649#issuecomment-1382667422

Please don't spam unrelated PRs.

**Pull request merged**
