### PR TITLE
Enable CR10S Onboard SD Card Reader

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Enable CR10S onboard SD card reader.

### Benefits

Onboard SD card reader works again.

### Related Issues

- https://github.com/MarlinFirmware/Configurations/issues/402

### CODE REVIEW

**Comment by thisiskeithb** [comment]
@thinkyhead: In https://github.com/MarlinFirmware/Marlin/issues/23518#issuecomment-1105652946, you mention that:
> `SDCARD_CONNECTION` doesn't apply to AVR boards.

I wonder why the UI / menu is different when `SDCARD_CONNECTION` enabled & set to `ONBOARD` as reported & shown in https://github.com/MarlinFirmware/Configurations/issues/402.

**Comment by thinkyhead** [comment]
> I wonder why the UI / menu is different when `SDCARD_CONNECTION` enabled & set to `ONBOARD` as reported & shown in #402.

They're looking at 2.0.7.2 and I don't think we have the same issue today.

**Comment by thinkyhead** [comment]
I see… The Creality RAMPS board is a special case.
```cpp
#ifndef SD_DETECT_PIN
  #if SD_CONNECTION_IS(ONBOARD)
    //#define HAS_ONBOARD_SD_DETECT               // If the SD_DETECT_PIN is wired up
  #endif
  #if ENABLED(HAS_ONBOARD_SD_DETECT) || !SD_CONNECTION_IS(ONBOARD)
    #define SD_DETECT_PIN                     49
  #endif
#endif
```

**Comment by thinkyhead** [comment]
The change was made in MarlinFirmware/Marlin#23740 by @ellensp so we'll need to look at the reason it was requested.

**Comment by thisiskeithb** [comment]
Oh, oops. I closed this too early then.

**Comment by thinkyhead** [comment]
In `pins_RAMPS.h` the `SD_DETECT_PIN` will end up being 49 (`EXP2_04_PIN`==`AUX3_02_PIN`) if there is an RRD LCD or `CR10_STOCKDISPLAY`. Without the common LCDs it is simply not assigned. The change proposed in this PR should not make any difference, except to prevent `SD_DETECT_PIN` being assigned the value 49 in the block shown above.

**Comment by thinkyhead** [comment]
The standard Creality3D V1.1.2 board has an onboard SD card and a single 10-pin connector for a stock display. There is no SD card on the stock display itself. However, `pins_RAMPS.h` still picks pin the same pin, 49, for any RAMPS that has that display, if no other value was previously given to `SD_DETECT_PIN`.

Anyway, it looks like what users might really want to do is enable `HAS_ONBOARD_SD_DETECT` to get the desired result, which then applies no matter which display is attached.

I'm not sure how you get an external SD card with the single 10-pin connector designed for the stock display, but maybe there are such units out there.

**Comment by thinkyhead** [comment]
I guess the "onboard" idiom is fine, and maybe there are some other AVR boards with built-in SD that could also use external SD, so we'll just patch them as we find them.

**Comment by InsanityAutomation** [comment]
> The standard Creality3D V1.1.2 board has an onboard SD card and a single 10-pin connector for a stock display. There is no SD card on the stock display itself. However, `pins_RAMPS.h` still picks pin the same pin, 49, for any RAMPS that has that display, if no other value was previously given to `SD_DETECT_PIN`.
> 
> Anyway, it looks like what users might really want to do is enable `HAS_ONBOARD_SD_DETECT` to get the desired result, which then applies no matter which display is attached.
> 
> I'm not sure how you get an external SD card with the single 10-pin connector designed for the stock display, but maybe there are such units out there.

The Creality ramps is the 2.2 with the 2 connector display. The older 1.1.4 etc board is a melzi / sanguino.

**Pull request merged**
