### PR TITLE
added Eryone Thinker SE based on Thinker V2 board (stock)

### LINKED ISSUE #356: Request: Eryone Thinker SE on Marlin 2.0.7.2
Eryone made available their configs for v2.0.x over [here](https://github.com/Eryone/mega2560), tho they fail to compile if put under 2.0.7.2 firmware.

Please take this printer into consideration too, I'm trying to enable manual mesh bed leveling and the latest 2.0 features, but I don't trust 2.0.x (probably beta) they provided enough to use it in "production".

Thank you very much in advance!!

### PR DESCRIPTION
**Pull request by bryanpedini**
source: https://github.com/Eryone/mega2560 + issue #356
with code courtesy of #ellensp

Co-authored-by: ellensp <ellensp@hotmail.com>

### Requirements

I think none

### Description

Brought Eryone's configuration with the much appreciate help of @ellensp and a bit of trial and error to the Thinker SE printer (on firmware configuration version: 2.0.7.2)

### Benefits

New printer configuration examples: Eryone Thinker SE with board Thinker V2

### Related Issues

feature request / definitively fixes #356

### CODE REVIEW

**Comment by ellensp** [comment]
Shouldn't #define MOTHERBOARD be BOARD_RAMBO_THINKERV2 like you just created?

**Comment by bryanpedini** [comment]
Ye, that's why pull is in draft and such... waiting for the pull on the main fw repo to get merged.

**Comment by bryanpedini** [comment]
All right @thinkyhead... thank you very much for your support (and Ellensp of course) for this printer!

**Comment by bryanpedini** [comment]
@thinkyhead sorry for the ping this late in the process, can I delete the head branch from my profile?
Thank you in advance!

**Comment by thinkyhead** [comment]
> can I delete the head branch from my profile?

Sorry, I don't get around to reviewing issues as much as I'd like these days. I assume by now you've read Git and GitHub documentation on branches and such, and have deleted all your old branches.

**Comment by bryanpedini** [comment]
Ya ya, I think so too (don't quite remember all that much what I get into and what not, too many projects and desire to learn that it's overwhelming).
Thank you for the information anyway!!

**Pull request merged**
