### PR TITLE
Ender 6

### PR DESCRIPTION
**Pull request by smcgroty**
### Requirements

* An Ender 6 with a Creality V4.3.1 motherboard
* Recommended: USB-serial console cable installed

### Description

Basic configuration for Ender 6 for standard and optional factory BLTouch configurations. Includes installation instructions for mainboard and LCD firmware.

### Related Issues

Help fulfill https://github.com/MarlinFirmware/Configurations/issues/311

### CODE REVIEW

**Comment by Majestix1970** [comment]
Hi
thank you for creating an Ender 6 setup....

Unfortunately I can not get it compiled with VS Code 1.54.1 and PlatformIO Core 5.1.0
and latest Marlin 2.0-bugfix nighly build (06 March 2021) and your original configuration.h and Configuration_adv.h (No changes at all)
I would appriciate your help.

Best regards
Eike

I get the following error:
<details><summary>Build Output</summary>

```
Processing STM32F103RET6_creality (platform: ststm32@~12.0; board: genericSTM32F103RE; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103RE.html
PLATFORM: ST STM32 (12.0.0) > STM32F103RE (64k RAM. 512k Flash)
HARDWARE: STM32F103RET6 72MHz, 64KB RAM, 512KB Flash
DEBUG: Current (jlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-arduinoststm32-maple 3.10000.201129 (1.0.0)
 - tool-stm32duino 1.0.2
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <SoftwareSerialM> 1.0.0
|-- <STM32ADC> 1.0
|-- <EEPROM>
|-- <USBComposite for STM32F1> 0.99
|-- <Wire> 1.0
|-- <Servo(STM32F1)> 1.1.2
Building in release mode
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\HAL.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\HAL_MinSerial.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\HAL_SPI.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\MarlinSerial.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\SPI.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\Servo.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_bl24cxx.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_flash.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_if_iic.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_sdcard.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_wired.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\fast_pwm.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\msc_sd.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\onboard_sd.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\sdio.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\tft\tft_fsmc.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\tft\tft_spi.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\tft\xpt2046.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\timers.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\watchdog.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\shared\Delay.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\shared\HAL_MinSerial.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\shared\eeprom_api.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\shared\esp_wifi.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\MarlinCore.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\core\serial.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\core\utility.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\babystep.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\bedlevel\abl\abl.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\bltouch.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\e_parser.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\pause.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\powerloss.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\feature\runout.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\bedlevel\G42.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\bedlevel\abl\G29.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\bedlevel\abl\M421.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M304.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M309.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M280.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M400.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M993_M994.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M997.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\control\T.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\pause\G27.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\pause\M125.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\pause\M600.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\pause\M603.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\pause\M701_M702.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\powerloss\M1000.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\powerloss\M413.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\feature\runout\M412.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\gcode.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\gcode_d.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\lcd\M0_M1.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\lcd\M117.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\lcd\M145.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\lcd\M300.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\lcd\M414.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\motion\M290.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\parser.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\probe\G30.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\probe\M401_M402.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\probe\M851.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\queue.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M1001.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M20.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M21_M22.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M23.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M24_M25.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M26.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M27.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M28_M29.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M30.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M32.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M33.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M34.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M524.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\sd\M928.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\stats\M31.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\stats\M75-M78.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\temp\M104_M109.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\temp\M105.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\temp\M106_M107.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\temp\M140_M190.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\temp\M141_M191.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\temp\M155.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\temp\M303.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\gcode\units\M82_M83.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\dgus_lcd.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\DGUSDisplay.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\fysetc\DGUSDisplayDef.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\fysetc\DGUSScreenHandler.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\extui\ui_api.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\fontutils.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\marlinui.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\libs\BL24CXX.cpp.o
Marlin\src\lcd\extui\lib\dgus\fysetc\DGUSScreenHandler.cpp:40:12: fatal error: ../../../../feature/powerloss.h: No such file or directory
   #include "../../../../feature/powerloss.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\fysetc\DGUSScreenHandler.cpp.o] Error 1
In file included from C:\Users\eiker\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/WString.h:29:0,
                 from C:\Users\eiker\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/wirish.h:47,
                 from C:\Users\eiker\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/Arduino.h:30,
                 from c:\users\eiker\desktop\marlin-bugfix-2.0.x\marlin\src\hal\shared\marduino.h:36,
                 from Marlin\src\lcd\extui\lib\dgus\../../../../inc/../HAL/./STM32F1/HAL.h:32,
                 from Marlin\src\lcd\extui\lib\dgus\../../../../inc/../HAL/HAL.h:30,
                 from Marlin\src\lcd\extui\lib\dgus\../../../../inc/MarlinConfig.h:31,
                 from Marlin\src\lcd\extui\lib\dgus\../../ui_api.h:45,
                 from Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.h:30,
                 from Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp:27:
Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::HandlePIDAutotune(DGUS_VP_Variable&, void*)':
C:\Users\eiker\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/avr/pgmspace.h:29:59: error: expected primary-expression before ')' token
 #define sprintf_P(s, f, ...) sprintf((s), (f), __VA_ARGS__)
                                                           ^
Marlin\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp:564:13: note: in expansion of macro 'sprintf_P'
             sprintf_P(buf, PSTR("M303 E-1 C5 S70 U1"));
             ^~~~~~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\lcd\extui\lib\dgus\DGUSScreenHandler.cpp.o] Error 1
===================================================== [FAILED] Took 25.94 seconds =====================================================

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  FAILED    00:00:25.936
================================================ 1 failed, 0 succeeded in 00:00:25.936 ================================================ 
The terminal process "C:\Users\eiker\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```
</details>

**Comment by thinkyhead** [comment]
@Majestix1970
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Tom's 3D Forums](https://forum.toms3d.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Majestix1970** [comment]
Hi Scott,
I am sorry, but this is a bug!
 I understand that my last comment was regarding support but only because I try to help fixing the original. I will restrein from from duing it here.

But fact is:  it is a Marlin bug that I can not compile the SW if the mentioned configuration is set.

So how should we proceed?
Best regards
Majestix


Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Scott Lahteine ***@***.***>
Gesendet: Thursday, April 15, 2021 1:38:04 PM
An: MarlinFirmware/Configurations ***@***.***>
Cc: Majestix1970 ***@***.***>; Mention ***@***.***>
Betreff: Re: [MarlinFirmware/Configurations] Ender 6 (#375)


@Majestix1970<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMajestix1970&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868600701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KIfxuqG4qLxIR2gASkKkZewDTMBMzZbtYZoxOvSGS2k%3D&reserved=0>
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on this page<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarlinFirmware%2FMarlin%2Fblob%2F2.0.x%2F.github%2Fcontributing.md%23i-dont-want-to-read-this-whole-thing-i-just-have-a-question&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868610655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UbFCT4SXKOHew9OGAMDWgkFNrYJdaDtzPa3RlfwYt4A%3D&reserved=0>.) For best results getting help with configuration and troubleshooting, please use the following resources:

  *   Marlin Discord server. Join link: https://discord.gg/n5NJ59y<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdiscord.gg%2Fn5NJ59y&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868610655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0koYtqqZ7sNdvBDdQ7y0aUmc82jJN5lSkL02%2BH6TUCc%3D&reserved=0>
  *   Facebook Group "Marlin Firmware"<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Fgroups%2F1049718498464482%2F&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868610655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qEFsAg3ueWw2y6R8DGLCiveORs67hnf6alsq2fWhjcI%3D&reserved=0>
  *   Facebook Group "Marlin Firmware for 3D Printers"<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Fgroups%2F3Dtechtalk%2F&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868620612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=I6WJhJ9Er0tcOunJlnSf6uV2HPt3wt0TzxT7%2BPjHpaY%3D&reserved=0>
  *   MarlinFW.org Marlin Documentation<https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmarlinfw.org%2F&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868620612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FAJJyPOtNA9mNPI9NWq%2FCnhOwhGmMtWf3HwR7H1aRDA%3D&reserved=0>
  *   Marlin Configuration<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fresults%3Fsearch_query%3Dmarlin%2Bconfiguration&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868620612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3ASfclCG3RN2KPMTTBpuYekG98LUWlhU0qWnkGgX0UE%3D&reserved=0> on YouTube
  *   Tom's 3D Forums<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforum.toms3d.org%2F&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868630570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MN6EyjZPAoVazeBD6IMalxiY0njzMqI3aygLC48q%2B%2FI%3D&reserved=0>
  *   RepRap.org Marlin Forum<https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fforums.reprap.org%2Flist.php%3F415&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868630570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uZc1uCXmdD1x6Itx4AR15qh%2BHe1KaF9YCnL6Mu80cfM%3D&reserved=0>

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarlinFirmware%2FMarlin%2Fissues%2Fnew%2Fchoose&data=04%7C01%7C%7C373dc1bb2b444329efd308d90002ef74%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540834868630570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jbwzs9wtOONNXt8%2FyOZ2D%2FzCLCp758%2FqLvRsSkXUdOM%3D&reserved=0>.

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thinkyhead** [comment]
Please use the resources linked above. This is not the appropriate place to demand help.

**Pull request merged**
