### PR TITLE
Ender 5 with SKR Mini E3 1.2

### PR DESCRIPTION
**Pull request by choppman**
### Requirements
Ender 5 Pro
Marlin 2.0.7.2
BigTreeTech SKR Mini E3 1.2

### Description
Added the Marlin 2.0.7.2 configuration files for the SKR Mini E3 v1.2

### Benefits

Don't have to figure out how to add the SKR Mini e3 v1.2 to the Ender 5 Pro

### Related Issues

No related issues.

### CODE REVIEW

**Comment by ellensp** [comment]
No included _Bootscreen.h and _Statusscreen.h files like all other Ender 5 Pro examples have.
Also SHOW_CUSTOM_BOOTSCREEN is disabled.  (perhaps ran out of flash ram?)

**Comment by ellensp** [comment]
This person has created separate PR for each file. 4 PR's in total...   very odd.  
So Files are there but in different PR's

**Comment by choppman** [comment]
I am very new to adding to github. i need a better understand how to add multiple files at once.I wanted to give back my profile I had to make for a Marlin E5-Pro as it doesn't have any of the SKR Mini e3 boards added.

As for comment out of show_custom_bootscreen I don't have it live on my ender 5 pro. It can be uncommented to allow for _boot.h to show.

**Comment by choppman** [comment]
I noticed I made this mistake also.
Put 
#define CONFIG_EXAMPLES_DIR "Creality/Ender-5/BigTreeTech SKR Mini E3 1.2"

Should be
#define CONFIG_EXAMPLES_DIR "Creality/Ender-5 Pro/BigTreeTech SKR Mini E3 1.2"

**Comment by ellensp** [comment]
Ender users expect to see the custom boot screen as default. please enable it for an example Config

**Comment by thisiskeithb** [comment]
> I noticed I made this mistake also.
> Put
> #define CONFIG_EXAMPLES_DIR "Creality/Ender-5/BigTreeTech SKR Mini E3 1.2"
> 
> Should be
> #define CONFIG_EXAMPLES_DIR "Creality/Ender-5 Pro/BigTreeTech SKR Mini E3 1.2"

This was removed and will be re-added at a later date.

**Comment by thinkyhead** [comment]
Please bring your submissions up to date with the current version 2.0.8 configurations as found in the import-2.0.x branch and combine all submissions into a single PR instead of creating multiple PRs with only one file in each.

**Comment by thinkyhead** [comment]
I cherry-picked your other branches into this one. Just needs to be brought up to date with the current 020008 config layout.

**Pull request merged**
