### PR TITLE
MakerTech3D

### PR DESCRIPTION
**Pull request by Fhalo48**
MakerTech 3D, Proforge 2s Dual.

### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Provide Configuration files for the MakerTech 3D, Proforge 2s Dual.

### Benefits

To upgrade the printer to marlin V2.1.x

### Related Issues

Use with caution not fully tested

### CODE REVIEW

**Comment by Fhalo48** [comment]
[Proforge2sDual.zip](https://github.com/MarlinFirmware/Configurations/files/9299854/Proforge2sDual.zip)

**Comment by thisiskeithb** [comment]
> [Proforge2sDual.zip](https://github.com/MarlinFirmware/Configurations/files/9299854/Proforge2sDual.zip)

These need to be added as another commit & not just a comment.

**Comment by Fhalo48** [comment]
I'm getting access denied when I try to push files. How do I commit?

**Comment by thisiskeithb** [comment]
Make sure you're pushing to your fork/branch ([Fhalo48:patch-1](https://github.com/Fhalo48/Configurations/tree/patch-1)) & not this repo. Changes will show up here.

**Comment by Fhalo48** [comment]
Thanks. That was the reason ;0

**Pull request merged**
