### PR TITLE
Add Anet ET4 configs

### PR DESCRIPTION
**Pull request by thinkyhead**
Configurations for some Anet models.

### CODE REVIEW

**Comment by chepo92** [comment]
I was looking for this, @thinkyhead which environment should be used in VScode/PIO with this to compile?

**Comment by thisiskeithb** [comment]
@chepo92 The existing ET4 config and the ones in this PR don't have proper board or environments in the main Marlin repo yet.

**Comment by thisiskeithb** [comment]
I just submitted a draft PR that adds Anet ET4 and ET4P board support (these boards are used in the ET4 and ET5): https://github.com/MarlinFirmware/Marlin/pull/20280

**Comment by Daniel-br0** [comment]
Keith,  hello. I have all et series models, created user menu with useful gcodes for the printers, ajusted all movements, etc. I would like to contribute, I can test things and share what I have created. There are still few bugs, like blobs during printing of complex mesh. This part I can't fix, it is probably some CPU problem. I am writing first time on github, sorry if it is a wrong brach.

**Pull request merged**
