### PR TITLE
align indent for temp residency, window & hysteresis

### PR DESCRIPTION
**Pull request by StuSerious**
### Requirements
This PR has no specific requirements!

### Description
Good Sunday everyone! This PR aims to apply the change over at https://github.com/MarlinFirmware/Marlin/pull/21329 to all config files in this repo.

### Benefits
Symmetry and order!

### Related Issues
This PR has no related Issues!

### TODOs:

- [ ] recursively check all files again
- [ ] find a more efficient way to replace changed values
- [ ] manually add files with different values set (this is going to take the most time)
- [ ] mark as ready and request review!

### CODE REVIEW

**Review by StuSerious — COMMENTED** [review]
these all look good and should need no further attention!

**Comment by StuSerious** [comment]
I underestimated the other config files, this is now officially a weekend project 😄 
hoping to get it done between today and tomorrow!

**Comment by thinkyhead** [comment]
A better weekend project is to learn regular expressions! But actually for the final cleanup I ended up just using "global search" and then scanning down the results list in the editor looking for lines that weren't aligned, then search-and-replacing other literal instances of the same misaligned contents. Took about 10 minutes to get them all.

**Comment by StuSerious** [comment]
@thinkyhead completely agree with you there. 
I apologize, I had overestimated my skill and underestimated the amount of work needed. 
Next time I'll open a PR it's going to be complete, and just needing review.

Again, my apologies.
Have a nice day!

~Ste

**Pull request merged**
