### PR TITLE
Ender 3 V2 has a 24v power supply, therefore motors are at 24v.

### PR DESCRIPTION
**Pull request by warewolf**
Ender 3 V2 has a 24v power supply, this corrects stealthchopper timings to use the 24v default rather than the 12v default.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Please redo this PR starting with the `import-2.0.x` branch and be careful to target the `import-2.0.x` branch when resubmitting the PR.

**Comment by warewolf** [comment]
I'm confused - I made separate pull requests each for import- and bugfix?

This one was against bugfix:
```
$ git log
commit 280da9ab4a8eeef6c13954478d8be2b29132f1fa (HEAD -> ender3v2_is_24v_not_12v, origin/ender3v2_is_24v_not_12v)
Author: Richard Harman <richard@richardharman.com>
Date:   Sun May 1 12:39:16 2022 -0400

    Ender 3 V2 has a 24v power supply, therefore motors are at 24v.

commit 9b1f32ae7e3471e1a76953af0ace96bf7148730c (upstream/bugfix-2.0.x)
```

and https://github.com/MarlinFirmware/Configurations/pull/724 is against import

**Comment by ellensp** [comment]
https://github.com/MarlinFirmware/Configurations/pull/724 is correct

configs for bugfix and release are auto generated from import. there is no need to do anything else

**Comment by warewolf** [comment]
:+1:

**Pull request closed without merging**
