### PR TITLE
fix: Ender-3 V2 / S1 DACAI LCD compatibility with custom UIs, improve LCD READMEs

### LINKED ISSUE #25195: [BUG] Ender 3 V2 with DACAI LCD not working with Landscape
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I bought an Ender 3 V2 with RET6 chip that came with a DACAI LCD screen that I believe is the same one used in the Ender 3 S1. This screen only updates by using private folder. I set `define DWIN_MARLINUI_LANDSCAPE` and it is still portrait, altough it does look offset on the progress bar.

Portrait mode also results in text being overwritten by other text instead of it being cleared, so eventually it looks like a jumbled mess and unreadable. Creality UI works fine without any issues, excluding lack of support for landscape mode.

This was tested on 2.1.2, 2.1.X, and bugfix-2.1.X

Also, I don't know if it's actually called DACAI or what, I think I read that somewhere.

### Bug Timeline

Present since at least 2.1.2

### Expected behavior

With Landscape set : Marlin UI to be in landscape mode
With Portrait set : UI to update the text properly by not overlaying on it but instead replacing it.

### Actual behavior

With Lanscape set : Marlin UI is in portrait mode with a lot of information cut off horizontally
With Portrait set : Text gets overwritten instead of replaced so eventually 0-9 are all on the same spot and makes it unreadable.

### Steps to Reproduce

For Landcsape error : Flash firmware with `define DWIN_MARLINUI_LANDSCAPE` on Ender 3 V2 with newer DACAI screen.
For Portrait error : Flash firmware with `define DWIN_MARLINUI_PORTRAIT` on Ender 3 V2 with newer DACAI screen.

### Version of Marlin Firmware

bugfix-2.1.X

### Printer model

Creality Ender 3 V2

### Electronics

Stock 4.2.2 RET6 board

### Add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10356774/configuration.zip)

### PR DESCRIPTION
**Pull request by vlad-the-compiler**
### Description

This PR fixes the `private` asset bundle folder for DACAI LCDs, making them compatible with custom UIs.

The following modifications have been made to the DACAI `private` folder:
* `config.txt` has been adjusted to allow the font sizes to match the DWIN display
    * Sourced from official Creality firmware
    * Text no longer draws out-of-bounds and now properly clears the background when it changes
* `truefont/font.ttf` has been changed from SimSun (serif) to SimHei (sans-serif)
    * Sourced from official Creality firmware
    * Font has been edited to include the Marlin Icons, MarlinUI now draws the Forward, Back, Degree, Feed Rate, and Folder font icons correctly
* The complete `DWIN_SET` graphics asset bundle has been converted into DACAI `ZICO` format
    * This brings the updated icons set to DACAI displays, allowing for custom UIs to render all icons correctly

Additionally, the `README.md` files for Ender-3 S1 and Ender-3 V2 `LCD Files` folders have been updated as follows:
* Ender-3 V2 `LCD Files/README.md`:
    * Now includes a full guide to identify all **4** types of display units (DWIN, DACAI, SYNWIT / VIEWE, TJC), along with their known specs
    * Includes a per-display UI compatibility list
    * Separate instructions have been added for flashing `DWIN` and `DACAI` LCDs
* The Ender-3 S1 `LCD Files/README.md` has been updated to a general notice regarding the different types of display, redirecting to the comprehensive Ender-3 V2 display family readme mentioned above

### Benefits

The DACAI LCD files update ensures this display unit now works properly with all Creality UI-based custom interfaces, and with MarlinUI. Text and icons are now displayed properly.
Please note that MarlinUI in Landscape is still not possible on this display, as the DACAI unit appears to omit the API for display rotation.

The updated `README.md` files provide more information about the different types of displays, their compatibility with the different UIs, and ways to update them (where currently available).

### Related Issues

Partially fixes https://github.com/MarlinFirmware/Marlin/issues/25195
Rendering issues are resolved, Landscape is incompatible due to display API limitations or currently unknown opcodes.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Some of the JPGs are increasing in size although they are not changing graphically. @ellensp recently compressed the images with JPEG.io so any images that are increasing in size should probably be run through that filter again.

**Comment by mriscoc** [comment]
Currently there are [two SYNWIT/VIEWE display versions](https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display). 
HAS_GCODE_PREVIEW must be disabled to use  ProUI with SYNWIT/VIEWE
TJC displays can be used with ProUI, but no values are shown in the mesh viewer due to missing small fonts.

**Comment by ellensp** [comment]
@mriscoc any chance you could update your page so the images are clickable to a larger image, not all of us have 20/20 vision...
Or just a link to a high res image...

**Comment by EvilGremlin** [comment]
I think we should pull this page both into general marlin docs and into creality conf directory.
Also move screen assets up from e3v2 dir.

**Comment by mriscoc** [comment]
> @mriscoc any chance you could update your page so the images are clickable to a larger image, not all of us have 20/20 vision... Or just a link to a high res image...

I will try to do it, but users give me low-res images.

**Comment by EvilGremlin** [comment]
I think @InsanityAutomation can make decent photos for all of them

**Comment by mriscoc** [comment]
> @mriscoc any chance you could update your page so the images are clickable to a larger image,

Done.

**Pull request merged**
