### PR TITLE
Create Readme.MD

### PR DESCRIPTION
**Pull request by akinilicali**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This should not be in the top level Anycubic folder and should be `README.md`, not `Readme.md`.

Also, you can add this as a commit in your other PR.

**Comment by akinilicali** [comment]
Sorry mate. I am new to this. I will try to fix them all.
________________________________

**Comment by thisiskeithb** [comment]
No worries. I just went through a big cleanup effort which included standardizing the readme files, so I'm pretty keen to keep things clean.

**Comment by akinilicali** [comment]
I will be glad to comply. Nice work by the way. Keep up the good work.
________________________________

**Comment by thisiskeithb** [comment]
Closing since you’ve added the readme to https://github.com/MarlinFirmware/Configurations/pull/732

**Pull request closed without merging**
