### PR TITLE
Configuration to CR-10 S5 with BTT SKR E3 mini V3

### PR DESCRIPTION
**Pull request by tiagofreire-pt**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

    - BLtouch v3.1 (connected to the Z endstop pin)
    - Stock LCD (connected to the LCD's EXT3 spare port, with one single straight ribbon cable)
    - Bondtech or stock extruder
    - Bowden setup
    - All 4 fans are PWM controlled.

### Benefits

New silent board, plug-and-play setup. All the 4 fans are PWM controlled, through the 3 fan board ports.

### Related Issues

N/A

### CODE REVIEW

**Comment by d-e-f-p** [comment]
@tiagofreire-pt I'm experiencing problems with this configuration. BL-Touch touches bed but it doesn't retract. 

Could you give some advice? have tried several configurations with no luck.

Thank you in advance.

**Comment by tiagofreire-pt** [comment]
@d-e-f-p , are you connecting the BLTouch on the 5 pin plug at the board or using the Z endstop pin?

The cable you are using is an official 5 united pin cable or has dupont pins?

Thanks.

**Comment by d-e-f-p** [comment]
I'm using z-stop pin and an extension cable thats ends in dupont  connectors to SKR. I have tried to use 'white' connectors too. It worked with original Creality board.

Do you think that the problem is related to cables? Can I do some test to verify it? (I will try to do a test without extension)

Thank you very much!

**Comment by tiagofreire-pt** [comment]
@d-e-f-p , check the correct pinout of your cable, as the original Creality v2.2 board has 2 pins switch out, on the 3 end-pin part (`PC14` + `GND`+ `PA1`)

image

**Comment by d-e-f-p** [comment]
@tiagofreire-pt First of all, thank you for your help and patience.

As far as I know, PC14 + GND+ PA1, are voltage and servo pins. This part seems to work because BLTouch responds to commands and self testing.  I'm trying configurations varying last two pins. 

My last test:
3 servo cables to Z-PROBE connector and 2 switch cables to zmin-endstop -> Crash to bed. Seems that 'touch' signal sent from BLTouch is not received by SKR.
All five cables to Z-PROBE connector and original switch to zmin-endstop -> It works if I let it click in zmin switch, as espected.

So, everything seems related to signal from BLTouch. How can I test it? I'm buying new cable to discard connectors or extensión.

**Comment by tiagofreire-pt** [comment]
The issue seems to be the cable pinout.

Switch the order on the 2-pin plug. (GND <> +5V).

**Comment by thisiskeithb** [comment]
@d-e-f-p: This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by d-e-f-p** [comment]
@thisiskeithb I'm sorry. Let me put only this last comment to confirm that configurations works fine. The problem was a defective extension cable.

@tiagofreire-pt Thank you for your help!

**Comment by capofranco** [comment]
Hello,
I upgraded my cr-10 S5 with skr mini E3 V3 and CR-touch. The CR touch works perfectly and responds to all commands from the BLTouch section. I used your preset. The problem is that when I autohome it gives me a stopped message on the screen. When I start printing, it performs an initial test and the nozzle is positioned in the center of the bed, but then it stops and does nothing. The job bar goes on as if it were printing, but very fast. The only doubt, CR-Touch is connected with its original extension, but it works well in all tests, I also left the Z endstop connected. But do I have to unplug it? 
Thanks, sorry for the stupid question but I'm freaking out about it. Bye

**Pull request merged**
