### PR TITLE
Add turnigy fabrikator configs

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

A Turnigy fabrikator

### Description

https://github.com/MarlinFirmware/Configurations/issues/649#issuecomment-1912778295 requested that the configs in 
https://github.com/PsychoOW/Turnigy-Fabrikator-Marlin-Firmware-Configuration  be added

### Benefits

Turnigy fabrikator has example configs

### Related Issues

https://github.com/MarlinFirmware/Configurations/issues/649#issuecomment-1912778295

### Notes

I just added the preexisting configs, I do not have this machine and cannot test these beyond compiling.

### CODE REVIEW

**Comment by ellensp** [comment]
@PsychoOW Please test these configs on Marlin bugfix 2.1.x  

To test this you need to comment out the these two lines in Configuration.h  
```
#error "Don't build with import-2.1.x configurations!"
#error "Use the 'bugfix...' or 'release...' configurations matching your Marlin version."

```

**Comment by PsychoOW** [comment]
Hello, i just saw it. Thank you so much for helping!! :) i am a bit overwhelmed right now how fast that went :O thank you so much! 
i will test it tomorow when i figured out githubs overlay lol all of that is very new for me.
i saw you removed a line with the fabrikator display i think. which is the standard display. but maybe i saw something wrong. I will definitely test it Asap! :) now i have unfortunatly to go to sleep, because i have to wake up very early.
I will get back to you asap :)

**Comment by PsychoOW** [comment]
> @PsychoOW Please test these configs on Marlin bugfix 2.1.x
> 
> To test this you need to comment out the these two lines in Configuration.h
> 
> ```
> #error "Don't build with import-2.1.x configurations!"
> #error "Use the 'bugfix...' or 'release...' configurations matching your Marlin version."
> ```

Hello, i just saw it. Thank you so much for helping!! :) i am a bit overwhelmed right now how fast that went :O thank you so much!
i will test it tomorow when i figured out githubs overlay lol all of that is very new for me.
i saw you removed a line with the fabrikator display i think. which is the standard display. but maybe i saw something wrong. I will definitely test it Asap! :) now i have unfortunatly to go to sleep, because i have to wake up very early.
I will get back to you asap :)

**Comment by PsychoOW** [comment]
> @PsychoOW Please test these configs on Marlin bugfix 2.1.x
> 
> To test this you need to comment out the these two lines in Configuration.h
> 
> ```
> #error "Don't build with import-2.1.x configurations!"
> #error "Use the 'bugfix...' or 'release...' configurations matching your Marlin version."
> ```

i cant upload it to printer unfortunatly. tried arduino ide and vs studio. compiling/verify work but upload itself not. i // the things you said.

**Comment by ellensp** [comment]
uploading has nothing to do with config files...
make sure your reboot before trying to upload, to make sure you have no other programs locking the serial port open (cura, pronterface etc)

**Comment by PsychoOW** [comment]
> uploading has nothing to do with config files... make sure your reboot before trying to upload, to make sure you have no other programs locking the serial port open (cura, pronterface etc)

Sorry with upload i meant flashing the device :)
anyways, you were right open cura was the problem. i have successfully installed bugfix firmware and can confirm it work. i also print level bed cubes and it works fine. homing worked perfectly too with the sensors. 

Amazing! all the hard work turned out perfect :) thank you so much for helping the last miles in order to add it to marlin firmware.

also i find it cool that you added the original Author :) 
i had to configure it back to stock Fabricator to make the printer print again. (it refused with the one from the original author due to missing aftermarket custom sensors(BLTouch)) if that matters. i am just happy to helped adding support for that device :D 

you are awesome !!! thank you so much!


so far it works fine, if i notice anything i will let you know :)

**Review by PsychoOW — APPROVED** [review]
The configuration works fine! Thanks alot!

The only thing I noticed was that Crashingdutchman is listed as author. But his settings were custom (added sensors etc.) and I had to configurate it back to "vanilla version" in order to make it useable for my  printer. So technically I made the changes and spend a lot time for it :-) 
Otherwise it works perfectly and I am very happy to see it. 

I am also going to be improving that configuration to make the best out of it without requirement for now Hardware (example mesh bed leveling). So everyone who has that printer will have all awesome functions that does not requires New Hardware and should work on everyone Single vanilla HK Printer.

**Review by PsychoOW — APPROVED** [review]
Works perfectly, please check my other review

**Review by PsychoOW — APPROVED** [review]
these configs work fine with bugfix version and the 2 lines commented out which ~~ellen~~ Peter told me to do

**Pull request merged**
