### PR TITLE
feat: initial commit Robo3D R1+

### PR DESCRIPTION
**Pull request by ncrmro**
### Description

Adds configuration for Robo3D R1+ printer

### Benefits

Adds configuration for Robo3D R1+ printer

Anything I missed that y'all thing should be in here I would appreciate. Otherwise this has been working for me.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Please compile against `bugfix-2.0.x` and make sure the configs have full parity with version 020006.

**Comment by ncrmro** [comment]
@thinkyhead just to confirm, you'd like me to rebase these on `bugfix-2.0.x` and make a pull request against that branch with version 020006?

**Comment by thinkyhead** [comment]
You should grab the latest files from the "defaults" folder in `import-2.0.x` and start with those. Apply your settings onto those files. Use whatever merge tool you like best. I typically just use GitHub Desktop to do it.

**Comment by ncrmro** [comment]
@thinkyhead should be good to go, just need to test. Will report back soon

**Comment by ncrmro** [comment]
Firmware woks fine.

**Comment by thinkyhead** [comment]
Thanks!

**Comment by ncrmro** [comment]
@thinkyhead sure thing :D

**Pull request merged**
