### PR TITLE
Add BIQU B1 base + BLTouch configs

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Add BIQU B1 base & BLTouch configs.

About the printer: The BIQU B1 is a 24v, i3-style 3D printer with a 235 x 235 x 270 mm build volume, Bowden extruder, filament runout detection (connected to TFT, so not useable in "Marlin Mode"), NeoPixel-compatible lighting in the hotend, DC heated bed, “Dual mode” TFT touch screen, and SKR 1.4 with TMC2225 drivers.

_Note: BIQU sent me this printer for feedback & to improve their Marlin config._

### Benefits

Users will have always up-to-date BIQU B1 configs.

### Related Issues

None.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
The hotend fan is always on, so I had to define `FAN1_PIN` as `-1` to get rid of the extra Fan Speed menu item.

If https://github.com/MarlinFirmware/Marlin/pull/18883 is accepted/merged, then I can remove the define & then set the number a fans in use instead.

**Comment by blueeagle69** [comment]
Hi Keith.

The Z max build volume is 270mm and not 370 😁
Loving this printer.

**Comment by thisiskeithb** [comment]
> Hi Keith.
> 
> The Z max build volume is 270mm and not 370 😁
> Loving this printer.

Thanks for letting me know about the typo. It's correct in the config.

**Comment by blueeagle69** [comment]
> > Hi Keith.
> > The Z max build volume is 270mm and not 370 😁
> > Loving this printer.
> 
> Thanks for letting me know about the typo. It's correct in the config.

No problem, and thank you for touching up the configs!
I meant to ask (if you know).
When my BTT smart filament sensor is connected to the dedicated port on the back, is this connected to the mainboard or the TFT?
I have a feeling it's connected to the TFT.

Thank you.

**Comment by thisiskeithb** [comment]
> When my BTT smart filament sensor is connected to the dedicated port on the back, is this connected to the mainboard or the TFT?

The existing filament runout sensor & addon smart filament runout sensors connect to the TFT.

It's easy enough to move to the motherboard and that's what I did with the existing filament runout sensor for my build since I primarily use the TFT in "Marlin Mode".

**Comment by blueeagle69** [comment]
Thanks Keith.
Yes sadly I'm quite comfortable around printer mainboards.  I have an SKR 1,3 on my beloved AM8.
I was planning on moving it. Looks like it may be a good idea 😃

**Pull request merged**
