### PR TITLE
Anycubic Mega Zero Marlin 2.0.5 configs, based on Anycubic's v0.0.4 FW

### PR DESCRIPTION
**Pull request by kad**
Config files are re-created based on the source code published at https://github.com/ANYCUBIC-3D/MEGA_ZERO

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the "`import`" branches and only later do we push them out as releases. Please redo this PR starting with the `import-2.0.x` branch and be careful to target `import-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `import-2.0.x`.

**Comment by thinkyhead** [comment]
Actually, I don't mind pitching into the 2.0.5 pile with this. But I'll also have to add this into `import-2.0.x` because there's no automatic interchange from here to there.

**Comment by kad** [comment]
thanks @thinkyhead !
BTW, it might be good to create Contributing.md for this repository, to show where and which patches are expected, and policies for patches to be accepted.

**Comment by thinkyhead** [comment]
Thanks for the suggestion. I will add one soon.

**Pull request merged**
