### PR TITLE
Replacing Screen files for the DACAI Screen.

### PR DESCRIPTION
**Pull request by MrMe1024**
They were not Exported with progressive turned off and Chroma quarter and as a result they did not display on the DACAI screen so I replaced them partly with the ones Creality offers and handmade 1.jpg as it was custom.

### Requirements

DACAI Screen

### Description

This is a simple update to the boot screen and other images in the examples/creality/ender 3v2/LCDfiles/private/images as they were not formatted correctly

### Benefits

fixes Boot screen and other images' compatibility causing them to display as they should on Creality ender 3v2 and other Creality printers that use the Dacai screen

### CODE REVIEW

**Comment by ellensp** [comment]
This was just tested with current Marlin with DWIN_CREALITY_LCD

IMG_2538

Yes the text is displayed, but text is out of position.

**Comment by ellensp** [comment]
using https://www.diffchecker.com/image-compare/ and comparing the marlin 1.jpg with yours shows a lot of text the positions has changed

**Comment by MrMe1024** [comment]
Alright. I changed that text image to keep more quality without making the file size larger but i will have to just settle with exporting the original at 100% quality and have a larger file. Will make the update soon.

**Comment by MrMe1024** [comment]
One question though. Why are you testing it on the DWIN LCD if it is for the DACAI display? I assume you changed the file name for that from 1.jpg to 1_English.jpg and put it in the DWIN_LCD folder to do that? Also Would this issue be the same for both displays when it is renamed and refied this way?

**Comment by ellensp** [comment]
Not using dwin_set folder, it on a DACAI using "private" folder

**Comment by ellensp** [comment]
https://marlin.crc.id.au/forum/t/identifying-ender-3-v2-screen-versions/960

**Comment by MrMe1024** [comment]
Ohh, i didn't know it could do that. Cool

**Comment by henryallen349** [comment]
Lol

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MrMe1024** [comment]
Sorry, I read it wrong. I though you had says that you could use the private files for the Dwin Screen.

**Pull request merged**
