### PR TITLE
Enable Linear Advance in Biqu Configs

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Enable Linear Advance in Biqu configs

### Benefits

Now that LA works on TMC2208/TMC2225 drivers, enable it!

### CODE REVIEW

**Comment by vovodroid** [comment]
Hi,
can I build it for B1 SE (not Plus)? The only difference is bed plate size?

**Comment by thisiskeithb** [comment]
> Hi,
> can I build it for B1 SE (not Plus)? The only difference is bed plate size?

Give it a try.

I have an early beta B1 SE (also non-plus), but didn’t think it was ever sold in retail, so I never submitted a config.

**Comment by vovodroid** [comment]
> didn’t think it was ever sold in retail,

I'm the lucky owner ))) Have place exactly for 41 cm. gantry

In general, is flushing new firmware is safe procedure? No bricking risk?

And actually I can flush B1 SE Plus and just set correct dimension in slicer?

**Comment by vovodroid** [comment]
> I never submitted a config.

Could you please?

**Comment by thisiskeithb** [comment]
I’ll chat with Biqu/BigTreeTech and see what’s up with the regular B1 SE.

**Comment by vovodroid** [comment]
> Give it a try.

Gave ))) When starting bed leveling it's preheating, homing in center, going to the left down corner, touching, goes a bit right, stops, and after a while returns to main screen with message "B1 SE ready".

The only things I have changed besides printer name are


```
#define X_BED_SIZE 235
#define Y_BED_SIZE 235

#define Z_MAX_POS 270
#define ALLOW_LOW_EJERK     // Allow a DEFAULT_EJERK value of <10. Recommended for direct drive hotends
```

ALLOW_LOW_EJERK as I converted to direct. I would like to enable linear advance, but rolled back to BTT touchscreen interface, as Biqu Marlin for SE doesn't work (it raise Z on homing).

**Comment by thisiskeithb** [comment]
That’s beyond the scope here, especially since you’ve modded your printer.

For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by vovodroid** [comment]
> That’s beyond the scope here,

Yes, but unfortunately there is no folder for SE (((. I hope you may upload your SE config after chat with Biqi/BTT. I'm ready to assist with tests/development.
SE indeed is very new product, but actually it also has SKR 2 REV B with 2225 drivers.

> especially since you’ve modded your printer.

I don't think ALLOW_LOW_EJERK can affect Z homing ))

**Comment by thisiskeithb** [comment]
> unfortunately there is no folder for SE

Because it never made it past the beta test stage and only a handful exist.

You're best hope is to modify the SE Plus config and adapt it to your printer mods. Please use the links in my comment above for further help since this Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here.

**Pull request merged**
