### PR TITLE
Add Artillery Genius Pro, other Artillery Config updates

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Add Artillery Genius Pro config and use nominal pulley values for other Artillery builds.

### Related Issues

- https://github.com/MarlinFirmware/Marlin/issues/23313
- https://github.com/MarlinFirmware/Marlin/issues/23393

### CODE REVIEW

**Comment by gudvinr** [comment]
> to do some PID tunes 

How can I do that?

**Comment by thisiskeithb** [comment]
> How can I do that?

With [`M303` - PID Autotune](https://marlinfw.org/docs/gcode/M303.html):

Auto-tune hotend at 210 °C for 8 cycles:
```
M303 E0 C8 S210
```

Auto-tune bed at 60 °C for 8 cycles:
```
M303 E-1 C8 S60
```

**Comment by gudvinr** [comment]
Is it necessary to do with 210 degrees for hotend? I ran with different temperatures and got different results. And after second run (all listed in order of execution) I also got different value.

<details>
<summary>M303 E0 C8 S210</summary>

```
Send: M303 E0 C8 S210
Recv: PID Autotune start
Recv:  bias: 61 d: 61 min: 208.01 max: 216.95 T:209.02 /0.00 B:23.87 /0.00 @:61 B@:0
Recv:  bias: 56 d: 56 min: 203.98 max: 212.44 T:209.94 /0.00 B:23.75 /0.00 @:56 B@:0
Recv:  bias: 55 d: 55 min: 203.87 max: 211.91 Ku: 17.41 Tu: 18.16
Recv:  Classic PID
Recv:  Kp: 10.45 Ki: 1.15 Kd: 23.72
Recv:  bias: 53 d: 53 min: 204.60 max: 211.91 Ku: 18.45 Tu: 18.16
Recv:  Classic PID
Recv:  Kp: 11.07 Ki: 1.22 Kd: 25.13
Recv:  bias: 53 d: 53 min: 204.98 max: 211.87 Ku: 19.58 Tu: 18.48
Recv:  Classic PID
Recv:  Kp: 11.75 Ki: 1.27 Kd: 27.14
Recv:  bias: 53 d: 53 min: 207.97 max: 211.89 Ku: 34.38 Tu: 18.80
Recv:  Classic PID
Recv:  Kp: 20.63 Ki: 2.19 Kd: 48.47
Recv:  bias: 53 d: 53 min: 203.75 max: 211.93 Ku: 16.49 Tu: 19.04
Recv:  Classic PID
Recv:  Kp: 9.90 Ki: 1.04 Kd: 23.55
Recv:  bias: 53 d: 53 min: 203.87 max: 212.01 Ku: 16.58 Tu: 19.20
Recv:  Classic PID
Recv:  Kp: 9.95 Ki: 1.04 Kd: 23.88
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_Kp 9.95
Recv: #define DEFAULT_Ki 1.04
Recv: #define DEFAULT_Kd 23.88
Recv: ok
```
</details>




<details>
<summary>M303 E0 C8 S195</summary>

```
Send: M303 E0 C8 S195
Recv: PID Autotune start
Recv:  bias: 51 d: 51 min: 193.84 max: 202.62 T:192.20 /0.00 B:23.89 /0.00 @:51 B@:0
Recv:  bias: 49 d: 49 min: 190.16 max: 196.83 T:194.32 /0.00 B:24.14 /0.00 @:49 B@:0
Recv:  bias: 47 d: 47 min: 190.38 max: 196.80 Ku: 18.64 Tu: 18.40
Recv:  Classic PID
Recv:  Kp: 11.18 Ki: 1.22 Kd: 25.72
Recv:  bias: 47 d: 47 min: 190.38 max: 196.43 Ku: 19.78 Tu: 17.76
Recv:  Classic PID
Recv:  Kp: 11.87 Ki: 1.34 Kd: 26.35
Recv:  bias: 47 d: 47 min: 193.51 max: 196.42 Ku: 41.10 Tu: 17.60
Recv:  Classic PID
Recv:  Kp: 24.66 Ki: 2.80 Kd: 54.25
Recv:  bias: 47 d: 47 min: 190.18 max: 196.62 Ku: 18.60 Tu: 18.32
Recv:  Classic PID
Recv:  Kp: 11.16 Ki: 1.22 Kd: 25.56
Recv:  bias: 47 d: 47 min: 190.45 max: 196.58 Ku: 19.55 Tu: 18.16
Recv:  Classic PID
Recv:  Kp: 11.73 Ki: 1.29 Kd: 26.63
Recv:  bias: 47 d: 47 min: 190.36 max: 196.56 Ku: 19.28 Tu: 18.40
Recv:  Classic PID
Recv:  Kp: 11.57 Ki: 1.26 Kd: 26.61
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_Kp 11.57
Recv: #define DEFAULT_Ki 1.26
Recv: #define DEFAULT_Kd 26.61
Recv: ok
```
</details>

<details>
<summary>M303 E0 C8 S225</summary>

```
Send: M303 E0 C8 S225
Recv: PID Autotune start
Recv:  bias: 64 d: 64 min: 217.42 max: 232.66 T:224.49 /0.00 B:24.41 /0.00 @:64 B@:0
Recv:  bias: 61 d: 61 min: 216.61 max: 228.12 T:224.46 /0.00 B:23.98 /0.00 @:61 B@:0
Recv:  bias: 60 d: 60 min: 223.12 max: 227.41 Ku: 35.69 Tu: 18.08
Recv:  Classic PID
Recv:  Kp: 21.41 Ki: 2.37 Kd: 48.39
Recv:  bias: 58 d: 58 min: 217.89 max: 227.41 Ku: 15.52 Tu: 17.92
Recv:  Classic PID
Recv:  Kp: 9.31 Ki: 1.04 Kd: 20.86
Recv:  bias: 58 d: 58 min: 217.66 max: 227.56 Ku: 14.91 Tu: 19.20
Recv:  Classic PID
Recv:  Kp: 8.95 Ki: 0.93 Kd: 21.47
Recv:  bias: 58 d: 58 min: 217.66 max: 227.59 Ku: 14.86 Tu: 18.80
Recv:  Classic PID
Recv:  Kp: 8.92 Ki: 0.95 Kd: 20.96
Recv:  bias: 58 d: 58 min: 223.10 max: 227.62 Ku: 32.66 Tu: 19.28
Recv:  Classic PID
Recv:  Kp: 19.60 Ki: 2.03 Kd: 47.23
Recv:  bias: 58 d: 58 min: 217.34 max: 227.44 Ku: 14.63 Tu: 18.80
Recv:  Classic PID
Recv:  Kp: 8.78 Ki: 0.93 Kd: 20.63
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_Kp 8.78
Recv: #define DEFAULT_Ki 0.93
Recv: #define DEFAULT_Kd 20.63
Recv: ok
```
</details>

<details>
<summary>M303 E0 C8 S210</summary>

```
Send: M303 E0 C8 S210
Recv: PID Autotune start
Recv:  bias: 55 d: 55 min: 208.77 max: 217.19 T:209.22 /0.00 B:24.34 /0.00 @:55 B@:0
Recv:  bias: 53 d: 53 min: 203.14 max: 212.07 T:206.48 /0.00 B:24.20 /0.00 @:53 B@:0
Recv:  bias: 53 d: 53 min: 203.99 max: 212.05 Ku: 16.75 Tu: 18.96
Recv:  Classic PID
Recv:  Kp: 10.05 Ki: 1.06 Kd: 23.82
Recv:  bias: 52 d: 52 min: 208.14 max: 211.87 Ku: 35.50 Tu: 18.48
Recv:  Classic PID
Recv:  Kp: 21.30 Ki: 2.30 Kd: 49.20
Recv:  bias: 52 d: 52 min: 208.09 max: 211.74 Ku: 36.26 Tu: 18.48
Recv:  Classic PID
Recv:  Kp: 21.75 Ki: 2.35 Kd: 50.25
Recv:  bias: 52 d: 52 min: 204.91 max: 211.86 Ku: 19.07 Tu: 18.56
Recv:  Classic PID
Recv:  Kp: 11.44 Ki: 1.23 Kd: 26.55
Recv:  bias: 52 d: 52 min: 207.99 max: 211.76 Ku: 35.13 Tu: 18.48
Recv:  Classic PID
Recv:  Kp: 21.08 Ki: 2.28 Kd: 48.69
Recv:  bias: 52 d: 52 min: 203.14 max: 211.86 Ku: 15.20 Tu: 18.80
Recv:  Classic PID
Recv:  Kp: 9.12 Ki: 0.97 Kd: 21.43
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_Kp 9.12
Recv: #define DEFAULT_Ki 0.97
Recv: #define DEFAULT_Kd 21.43
Recv: ok
```
</details>

**Comment by gudvinr** [comment]
Test runs for bed. Same thing, when I run autotune for 60 degrees when bed is warm it shows different values.

<details>
<summary>M303 E-1 C8 S60</summary>

```
Send: M303 E-1 C8 S60
Recv: PID Autotune start
Recv:  bias: 34 d: 34 min: 59.81 max: 61.13 T:60.83 /0.00 B:59.85 /0.00 @:0 B@:34
Recv:  bias: 24 d: 24 min: 59.64 max: 60.43 T:56.59 /0.00 B:59.90 /0.00 @:0 B@:24
Recv:  bias: 21 d: 21 min: 59.72 max: 60.27 Ku: 97.91 Tu: 36.48
Recv:  No overshoot
Recv:  Kp: 19.58 Ki: 1.07 Kd: 238.13
Recv:  bias: 20 d: 20 min: 59.77 max: 60.27 Ku: 101.74 Tu: 35.44
Recv:  No overshoot
Recv:  Kp: 20.35 Ki: 1.15 Kd: 240.38
Recv:  bias: 20 d: 20 min: 59.80 max: 60.24 Ku: 114.48 Tu: 34.00
Recv:  No overshoot
Recv:  Kp: 22.90 Ki: 1.35 Kd: 259.49
Recv:  bias: 20 d: 20 min: 59.82 max: 60.23 Ku: 125.05 Tu: 35.60
Recv:  No overshoot
Recv:  Kp: 25.01 Ki: 1.41 Kd: 296.79
Recv:  bias: 20 d: 20 min: 59.82 max: 60.21 Ku: 128.48 Tu: 34.48
Recv:  No overshoot
Recv:  Kp: 25.70 Ki: 1.49 Kd: 295.32
Recv:  bias: 20 d: 20 min: 59.77 max: 60.23 Ku: 110.87 Tu: 32.64
Recv:  No overshoot
Recv:  Kp: 22.17 Ki: 1.36 Kd: 241.26
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_bedKp 22.17
Recv: #define DEFAULT_bedKi 1.36
Recv: #define DEFAULT_bedKd 241.26
Recv: ok
```
</details>


<details>
<summary>M303 E-1 C8 S40</summary>

```
Send: M303 E-1 C8 S40
Recv: PID Autotune start
Recv:  bias: 20 d: 20 min: 39.97 max: 42.10 T:28.20 /0.00 B:40.07 /0.00 @:0 B@:20
Recv:  bias: 20 d: 20 min: 39.96 max: 40.32 T:28.10 /0.00 B:39.99 /0.00 @:0 B@:20
Recv:  bias: 20 d: 20 min: 39.95 max: 40.37 Ku: 121.34 Tu: 26.08
Recv:  No overshoot
Recv:  Kp: 24.27 Ki: 1.86 Kd: 210.97
Recv:  bias: 20 d: 20 min: 39.96 max: 40.32 Ku: 140.16 Tu: 23.52
Recv:  No overshoot
Recv:  Kp: 28.03 Ki: 2.38 Kd: 219.78
Recv:  bias: 20 d: 20 min: 39.98 max: 40.38 Ku: 128.07 Tu: 27.92
Recv:  No overshoot
Recv:  Kp: 25.61 Ki: 1.83 Kd: 238.38
Recv:  bias: 20 d: 20 min: 39.95 max: 40.27 Ku: 159.84 Tu: 27.12
Recv:  No overshoot
Recv:  Kp: 31.97 Ki: 2.36 Kd: 288.99
Recv:  bias: 20 d: 20 min: 39.93 max: 40.19 Ku: 191.51 Tu: 10.32
Recv:  No overshoot
Recv:  Kp: 38.30 Ki: 7.42 Kd: 131.76
Recv:  bias: 20 d: 20 min: 39.97 max: 40.40 Ku: 116.90 Tu: 38.56
Recv:  No overshoot
Recv:  Kp: 23.38 Ki: 1.21 Kd: 300.52
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_bedKp 23.38
Recv: #define DEFAULT_bedKi 1.21
Recv: #define DEFAULT_bedKd 300.52
Recv: ok
```
</details>

<details>
<summary>M303 E-1 C8 S60</summary>

```
Send: M303 E-1 C8 S60
Recv: PID Autotune start
Recv:  bias: 29 d: 29 min: 59.69 max: 61.48 T:27.23 /0.00 B:59.99 /0.00 @:0 B@:29
Recv:  bias: 23 d: 23 min: 59.76 max: 60.22 T:27.66 /0.00 B:59.97 /0.00 @:0 B@:23
Recv:  bias: 20 d: 20 min: 59.78 max: 60.17 Ku: 130.86 Tu: 28.00
Recv:  No overshoot
Recv:  Kp: 26.17 Ki: 1.87 Kd: 244.28
Recv:  bias: 20 d: 20 min: 59.79 max: 60.19 Ku: 127.55 Tu: 31.68
Recv:  No overshoot
Recv:  Kp: 25.51 Ki: 1.61 Kd: 269.38
Recv:  bias: 20 d: 20 min: 59.75 max: 60.20 Ku: 111.58 Tu: 32.32
Recv:  No overshoot
Recv:  Kp: 22.32 Ki: 1.38 Kd: 240.41
Recv:  bias: 20 d: 20 min: 59.78 max: 60.24 Ku: 109.66 Tu: 35.36
Recv:  No overshoot
Recv:  Kp: 21.93 Ki: 1.24 Kd: 258.52
Recv:  bias: 27 d: 27 min: 59.80 max: 60.00 Ku: 352.03 Tu: 16.24
Recv:  No overshoot
Recv:  Kp: 70.41 Ki: 8.67 Kd: 381.13
Recv:  bias: 20 d: 20 min: 59.88 max: 60.23 Ku: 148.53 Tu: 22.48
Recv:  No overshoot
Recv:  Kp: 29.71 Ki: 2.64 Kd: 222.60
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_bedKp 29.71
Recv: #define DEFAULT_bedKi 2.64
Recv: #define DEFAULT_bedKd 222.60
Recv: ok
```
</details>

<details>
<summary>M303 E-1 C8 S80</summary>

```
Send: M303 E-1 C8 S80
Recv: PID Autotune start
Recv:  bias: 46 d: 46 min: 79.69 max: 81.32 T:28.10 /0.00 B:79.92 /0.00 @:0 B@:46
Recv:  bias: 39 d: 39 min: 79.64 max: 80.43 T:28.24 /0.00 B:79.87 /0.00 @:0 B@:39
Recv:  bias: 35 d: 35 min: 79.71 max: 80.33 Ku: 144.99 Tu: 34.64
Recv:  No overshoot
Recv:  Kp: 29.00 Ki: 1.67 Kd: 334.83
Recv:  bias: 34 d: 34 min: 79.76 max: 80.24 Ku: 182.91 Tu: 32.80
Recv:  No overshoot
Recv:  Kp: 36.58 Ki: 2.23 Kd: 399.96
Recv:  bias: 33 d: 33 min: 79.73 max: 80.24 Ku: 166.00 Tu: 32.56
Recv:  No overshoot
Recv:  Kp: 33.20 Ki: 2.04 Kd: 360.33
Recv:  bias: 33 d: 33 min: 79.76 max: 80.20 Ku: 192.02 Tu: 31.28
Recv:  No overshoot
Recv:  Kp: 38.40 Ki: 2.46 Kd: 400.43
Recv:  bias: 32 d: 32 min: 79.78 max: 80.21 Ku: 186.55 Tu: 30.96
Recv:  No overshoot
Recv:  Kp: 37.31 Ki: 2.41 Kd: 385.03
Recv:  bias: 32 d: 32 min: 79.73 max: 80.22 Ku: 165.25 Tu: 32.08
Recv:  No overshoot
Recv:  Kp: 33.05 Ki: 2.06 Kd: 353.42
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_bedKp 33.05
Recv: #define DEFAULT_bedKi 2.06
Recv: #define DEFAULT_bedKd 353.42
Recv: ok
```
</details>

**Comment by thisiskeithb** [comment]
> Is it necessary to do with 210 degrees for hotend?

210 is a good standard for PLA these days.

Thanks for running the PID tests! It appears that Artillery copied the bed PID values to the hotend, so I've made those corrections.

**Comment by ellensp** [comment]
linking to https://github.com/MarlinFirmware/Marlin/issues/23393 
"Artillery Genius Pro (Ruby 32bit) Does not Boot"

**Pull request merged**
