### PR TITLE
🔥 Remove more TMC26X

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Followup to 4e9493f / https://github.com/MarlinFirmware/Marlin/pull/26770

### Benefits

Removes dead config options

### Related Issues

- 4e9493f
- https://github.com/MarlinFirmware/Marlin/pull/26770

### CODE REVIEW

**Comment by thisiskeithb** [comment]
CI will fail due to a handful of Geeetech configs that still won't build correctly due to some [LCD/library incompatibilities](https://github.com/MarlinFirmware/Marlin/issues/26571) after https://github.com/MarlinFirmware/Marlin/commit/ec7ab5a277a0210e1349f9e8608c372e40fdb6e6.

**Comment by thisiskeithb** [comment]
...PR fixed after recent force-pushes to `import-2.1.x`, but my comment above is still applicable.

**Comment by sjasonsmith** [comment]
I'm not sure what process @thinkyhead uses to deploy updated Configuration files across all the examples. This might be something that he has some automation around, or perhaps you are already using the same tools he does?

**Comment by thisiskeithb** [comment]
> I'm not sure what process @thinkyhead uses to deploy updated Configuration files across all the examples. This might be something that he has some automation around, or perhaps you are already using the same tools he does?

Find and replace 💪 …along with a manual check to make sure nothing was missed due to the custom nature of some configs.

**Comment by thisiskeithb** [comment]
Rebased on current `import-2.1.x` and I've removed this code from the recently added configs.

**Comment by thisiskeithb** [comment]
> CI will fail due to a handful of Geeetech configs that still won't build correctly due to some [LCD/library incompatibilities](https://github.com/MarlinFirmware/Marlin/issues/26571) after [MarlinFirmware/Marlin@ec7ab5a](https://github.com/MarlinFirmware/Marlin/commit/ec7ab5a277a0210e1349f9e8608c372e40fdb6e6).

...and apparently some other recent changes:

```prolog
HEAD is now at f5cf667c95 🎨 Clarify some string parameters (#26949)
Building Configurations in config/examples/CNC/miniRambo ...
Building environment rambo for board MINIRAMBO (1201)...

In file included from Marlin/src/gcode/feature/digipot/../../../inc/MarlinConfigPre.h:37:0,
                 from Marlin/src/gcode/feature/digipot/../../../inc/MarlinConfig.h:28,
                 from Marlin/src/gcode/feature/digipot/M907-M910.cpp:23:
Marlin/src/gcode/feature/digipot/M907-M910.cpp: In static member function 'static void GcodeSuite::M907_report(bool)':
Marlin/src/gcode/feature/digipot/M907-M910.cpp:137:13: error: 'SP_E_STR' was not declared in this scope
           , SP_E_STR,       stepper.motor_current_setting[2]  // E
             ^
```

Edit: This CNC config was committed directly so it was not checked by CI: e7254f1

**Comment by thinkyhead** [comment]
> apparently some other recent changes 

Should now be sorted out by tweaks to Motor Current PWM pin handling.

**Pull request closed without merging**
