### PR TITLE
✨ Add Experimental Ultimaker 2 config

### PR DESCRIPTION
**Pull request by kallisti5**
### Requirements

* Ultimaker 2
* Ultimaker 2+
  * With some tweaks, maybe in the future i'll push a dedicated Ultimaker 2+ directory once this one is 100% working.

### Description

A Configuration to use Marlin 2 on the Ultimaker 2  (Ultimaker's last "open" printer)

### CODE REVIEW

**Comment by kallisti5** [comment]
~This one should not be merged yet.  See https://github.com/MarlinFirmware/Marlin/issues/22945 for why. (The UltiLCD2 code was never upstreamed so the LCD won't work)~

Nevermind! BOARD_ULTIMAIN_2 seems to support the LCD out of the box. :sparkle:

**Comment by kallisti5** [comment]
This code is based on a conversion of the original Marlin 1.x Configuration.h from Ultimaker.  It compiles, but hasn't been tested yet.

**Comment by kallisti5** [comment]
marlin2

Proof of life :-)

**Comment by kallisti5** [comment]
**Status:**

* :heavy_check_mark:  LCD
* :yellow_circle: Input knob 
  * knob reverse direction
* :heavy_check_mark: SD Card
* :heavy_check_mark: Hot end fans
* :heavy_check_mark: Hot end thermocouple
* :heavy_check_mark: Hot end heater
* :heavy_check_mark: Bed thermocouple 
* :heavy_check_mark: Bed heater
* :x: Lights
  * off
* :yellow_circle: X
  * moves, home position ok. Collision at end of bed on right side when advanced
* :yellow_circle: Y
  * moves. Inversion likely incorrect?   front is 0, back (home) is +xxx
* :yellow_circle: Z
  * moves.  Slow movement however, max speed increase needed

**Comment by kallisti5** [comment]
**Status:**

* :heavy_check_mark:  LCD
* :yellow_circle: Input knob 
  * knob reverse direction vs Ultimaker/Tinkergnome firmware
* :heavy_check_mark: SD Card
* :heavy_check_mark: Hot end fans
* :heavy_check_mark: Hot end thermocouple
* :heavy_check_mark: Hot end heater
* :heavy_check_mark: Bed thermocouple 
* :heavy_check_mark: Bed heater
* :x: Lights
  * off.  No support in Marlin for single color LED's? PWM pin 8
* :heavy_check_mark:  Home action
* :heavy_check_mark:  X axis
* :yellow_circle: Y axis
  * moves. Inversion incorrect?   front is 0, back (home) is +224
* :yellow_circle: Z axis
  * moves.  Slow movement however, max speed increase needed
* :x: Extruder 0
  * No movement.  Need to confirm pins

**Comment by ManuelMcLure** [comment]
For Lights, would `CASE_LIGHT_ENABLE` apply? That allows for a single brightness-controlled LED.

**Comment by kallisti5** [comment]
> For Lights, would `CASE_LIGHT_ENABLE` apply? That allows for a single brightness-controlled LED.

Nice catch! There's no CASE_LIGHT_ENABLE in the example Configuration.h    Adding it flips the case light on.

**Comment by ManuelMcLure** [comment]
It’s in Configuration_adv.h.

**Comment by kallisti5** [comment]
* Enabled bed leveling
* Increased feedrates for homing and manual
* Enabled case light
* Reduced Z height to 210 to reduce the severity of bed collisions. 210 represents a fully downward adjusted bed plus + a little bit.

**Status:**
* :heavy_check_mark:  LCD
* :yellow_circle: Input knob 
  * knob reverse direction vs Ultimaker/Tinkergnome firmware
  * ~2-3 rotational clicks == moving one menu item.  How to adjust sensitivity?
* :heavy_check_mark: SD Card
* :heavy_check_mark: Hot end fans
* :heavy_check_mark: Hot end thermocouple
* :heavy_check_mark: Hot end heater
* :heavy_check_mark: Bed thermocouple 
* :heavy_check_mark: Bed heater
* :heavy_check_mark: Lights
* :heavy_check_mark:  Home action
* :heavy_check_mark:  X axis
* :yellow_circle: Y axis
  * moves. Inversion incorrect?   front is 0, back (home) is +224.  Unsure on why Ultimaker was doing this.
* :heavy_check_mark: Z axis
* :x: Extruder 0
  * No movement.  Need to confirm pins
* :x: Bed leveling
  * The Ultimaker firmware had a 20-30mm bed offset at the beginning of leveling, you then slowly dialed the Z axis up before beginning the final tweaks.  Does this feature exist in upstream Marlin?

**Comment by ManuelMcLure** [comment]
> * 🟡 Y axis
>   
>   * moves. Inversion incorrect?   front is 0, back (home) is +224.  Unsure on why Ultimaker was doing this.

That sounds right for a printer that homes to Ymax. By definition the front left corner of the bed is 0,0.

**Comment by kallisti5** [comment]
* Enabled speaker. Click sound functional

**Status:**
* :heavy_check_mark:  LCD
* :yellow_circle: Input knob 
  * knob reverse direction vs Ultimaker/Tinkergnome firmware
  * ~2-3 rotational clicks == moving one menu item.  How to adjust sensitivity?
* :heavy_check_mark: SD Card
* :heavy_check_mark: Hot end fans
* :heavy_check_mark: Hot end thermocouple
* :heavy_check_mark: Hot end heater
* :heavy_check_mark: Bed thermocouple 
* :heavy_check_mark: Bed heater
* :heavy_check_mark: Speaker
* :heavy_check_mark: Lights
* :heavy_check_mark:  Home action
* :heavy_check_mark: X axis
* :heavy_check_mark: Y axis
* :heavy_check_mark: Z axis
* :x: Extruder 0
  * No movement.  Need to confirm pins
* :x: Bed leveling
  * The Ultimaker firmware had a 20-30mm bed offset at the beginning of leveling, you then slowly dialed the Z axis up before beginning the final tweaks.  Does this feature exist in upstream Marlin?
  * This seems to be a custom feature of Ultimaker?  Bed fully lowered is pos 0.  Bed at full height is MAX.   I guess I just need to precisely tune the Z height and then the bed leveling will handle the remaining few mm which can be screw adjusted?

**Comment by ellensp** [comment]
Look under 
//
// ENCODER SETTINGS
//

**Comment by kallisti5** [comment]
* Adjust Z_MAX_POS from 220 to 213.  Aligns a fully homed bed fully compressed just under nozzle with room to adjust upward.
* Reduce ENCODER pulses per step to 1 to bring "one click" closer to moving one menu item.
* Reverse ENCODER direction to fix direction of travel.


**Status:**
* :heavy_check_mark:  LCD
* :heavy_check_mark: Input knob 
* :heavy_check_mark: SD Card
* :heavy_check_mark: Hot end fans
* :heavy_check_mark: Hot end thermocouple
* :heavy_check_mark: Hot end heater
* :heavy_check_mark: Bed thermocouple 
* :heavy_check_mark: Bed heater
* :heavy_check_mark: Speaker
* :heavy_check_mark: Lights
* :heavy_check_mark:  Home action
* :heavy_check_mark: X axis
* :heavy_check_mark: Y axis
* :heavy_check_mark: Z axis
* :yellow_circle: : Extruder 0
  * Movement ok when hotend > 170C and direction seems correct.
  * No menu to change material.  Bowden is ~ 705mm long
* :x: Bed leveling
  * The Ultimaker firmware had a 20-30mm bed offset at the beginning of leveling, you then slowly dialed the Z axis up before beginning the final tweaks.  Does this feature exist in upstream Marlin?
  * This seems to be a custom feature of Ultimaker?  Bed fully lowered is pos 0.  Bed at full height is MAX.   I guess I just need to precisely tune the Z height and then the bed leveling will handle the remaining few mm which can be screw adjusted?
  * I started a print with a cold hot end to test the leveling. Post a successful bed leveling, the nozzle is ~10mm from the bed on layer 0 :-|

**Comment by kallisti5** [comment]
So, overall there are a few deficiencies left that seem to be due to lack of stock Marlin support:
* Bed Leveling is a little sketchy. The creep-up-with-the-knob feature in the Ultimaker fork was nice and pretty much eliminate bed-collisions.
  * Level bed option
  * Bring Z axis ~50mm from nozzle
  * Instructions "turn knob until nozzle is 1mm from bed. Press to continue"
  * Z axis goes up ~0.5mm.  3 point bed leveling begins with sheet of paper + turning bed screws.
* No guided material change process?  The Ultimaker fork had a material change feature that:
  * heat up
  * retract material ~ - 700mm at a fast rate to eject it from the bowden tube
  * wait for user to load new material
  * Push knob to begin slowly accepting material into extruder
  * Push knob once inserted to move the material ~ + 700mm to the nozzle.

Both of these are nice to haves, and might represent new feature options that could be added to Marlin 2.x

As for bugs left in this config, there's one.   After leveling, the print head seems to print layer 0 ~10mm away from the bed.

**Comment by ManuelMcLure** [comment]
> * No guided material change process?  The Ultimaker fork had a material change feature that:
>   
>   * heat up
>   * retract material ~ - 700mm at a fast rate to eject it from the bowden tube
>   * wait for user to load new material
>   * Push knob to begin slowly accepting material into extruder
>   * Push knob once inserted to move the material ~ + 700mm to the nozzle.

Most of this is supported as part of `ADVANCED_PAUSE_FEATURE` - the only thing I don't think is supported is waiting for a second button press between the last two steps - instead it will do a slow load (to get the filament between the extruder gears) , fast load (to get to the end of the bowden), and purge after a single button press.

**Comment by kallisti5** [comment]
Correct again. ADVANCED_PAUSE added the material change menu :-)  Works fine.

* Enabled ADVANCED_PAUSE for material changing
* Added preheat shortcut menu items to match Ultimaker Marlin style
* Lightly tuned FILAMENT_CHANGE_FEEDRATE / LENGTH.  I have an E3D Titan geared extruder, so it may not match stock... more investigation needed.

**Status:**
* :heavy_check_mark:  LCD
* :heavy_check_mark: Input knob 
* :heavy_check_mark: SD Card
* :heavy_check_mark: Hot end fans
* :heavy_check_mark: Hot end thermocouple
* :heavy_check_mark: Hot end heater
* :heavy_check_mark: Bed thermocouple 
* :heavy_check_mark: Bed heater
* :heavy_check_mark: Speaker
* :heavy_check_mark: Lights
* :heavy_check_mark:  Home action
* :heavy_check_mark: X axis
* :heavy_check_mark: Y axis
* :heavy_check_mark: Z axis
* :heavy_check_mark: : Extruder 0
* :x: : Bed leveling
  * The Ultimaker firmware had a 20-30mm bed offset at the beginning of leveling, you then slowly dialed the Z axis up before beginning the final tweaks.  Does this feature exist in upstream Marlin?
  * This seems to be a custom feature of Ultimaker?  Bed fully lowered is pos 0.  Bed at full height is MAX.   I guess I just need to precisely tune the Z height and then the bed leveling will handle the remaining few mm which can be screw adjusted?
  * I started a print with a cold hot end to test the leveling. Post a successful bed leveling, the nozzle is ~10mm from the bed on layer 0 :-|

**Comment by kallisti5** [comment]
* Added TUNE keyword to quickly search for adjustments for various common Ultimaker 2 Upgrades

Example:
```C
// TUNE Ultimaker 2 Extruder
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 200, 282 } // UM2 Stock Extruder (black box)
//#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 200, 369 } // UM2+ (white box)
//#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 200, 846 } // UM2 w/E3D Titan
```

**Comment by kallisti5** [comment]
* Tuned UM2 + E2D Titan Extruder based on standard 100mm extrusion.
  * UM2 +and UM2+ extruder steps per mm are based on Marlin 1.x settings and might need adjusted.
* Changed serial uart to more compatible 115200
  *  Couldn't get reliable terminal commands on 250000 baud

**Comment by thisiskeithb** [comment]
> UM2 +and UM2+ extruder steps per mm are based on Marlin 1.x settings and might need adjusted.

The values for each axis won’t change, but they will be in a different format.

**Comment by kallisti5** [comment]
Ok.  Down to bed height weirdness even post successful calibration.

* Calibrate bed (this printer has no bed probes for leveling, all manual)
  * Using 3-point leveling
  * What's the point of the +0.20 adjustment on each Z calibration step?   It asks for each of all three Z points which seems weird.
* Save
* Begin print.  Nozzle starts layer zero like 5mm in the air from the bed :-|

Also a few quirks:
* Bed doesn't retract back to Z_MAX when print cancelled / bed calibration complete?
* No pre-dump of material at 0,0 before printing (could be a ultimaker firmware thing)


On the bright side I was able to print a bloby circle which looked pretty even, so X/Y seem ballpark ok.

**Comment by thinkyhead** [comment]
> What's the point of the +0.20 adjustment on each Z calibration step?

A small value but not too small, to hopefully give space for paper. Modify `MANUAL_PROBE_START_Z`.

> Bed doesn't retract back to `Z_MAX` when print cancelled / bed calibration complete?

There is an option `EVENT_GCODE_SD_ABORT` for an aborted SD print, which by default just re-homes XY.

> No pre-dump of material at 0,0 before printing (could be a ultimaker firmware thing)

Ideally this should be done as a `G12` move, requiring `NOZZLE_CLEAN_FEATURE` so the same G-code works on a variety of printers, but you may also add specific pre-print dump moves to your slicer settings.

**Comment by thinkyhead** [comment]
> As for bugs left in this config, there's one. After leveling, the print head seems to print layer 0 ~10mm away from the bed.

- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to the printer from a host such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to apply factory settings.
- Issue the command `M111 S247` to enable maximum logging.
- Send `G28` to do the standard homing procedure.
- Send `G29` to probe the bed and enable bed leveling.
- Do some moves that reveal the Z height problem.
- Examine the log output to see if there is some obvious settings problem.
- Copy the log output into a **.TXT file** and attach it to your next reply.

It may also work to just add `M111 S247` to your G-code file and then just run the print until the point where it starts printing in the air.

**Comment by kallisti5** [comment]
Weird... after:

1) Enabling DEBUG leveling and M114_DETAILS
2) Sending M502 and M500
3) Issuing M111 S247
4) Doing G28, G29, G29, G29
5) Updating Marlin from d0c0630c1f91cb43dc23c1ed9e4c166d284785eb to b18aa933d14f9761d74b19be79db64e21356c563

The print is now at the correct bed-leveled height.

text file attached incase it's still useful. (ignore the  "cold extrusion prevented") error.   I forgot to preheat and restarted the machine.

[log.txt](https://github.com/MarlinFirmware/Configurations/files/7353690/log.txt)

**Comment by kallisti5** [comment]
Looks like I need to ramp up my cooling fans lol.   Best print so far though with Marlin 2 on the Ultimaker 2 :grin: 

photo_2021-10-15_08-29-06

**Comment by kallisti5** [comment]
Thanks for merging this one!  There are a few bugs left.. namely:

* Over-extrusion on walls + "soft" prints.
  * 100mm extrusion test is passing... so doesn't seem to be an issue there.
  * Cooling fan running expected speeds.  100% doesn't fix the issue.
* Bed leveling still gets weird and "floats" randomly.

I'm back on Ultimaker's Marlin 1 branch for now because I need a functional printer.  Let me know if anyone needs any testing though.  I might take another crack at fixing the few remaining issues.

**Comment by thisiskeithb** [comment]
If you zip up your Marlin 1.x config and attach it here, I’ll see if anything stands out.

**Comment by kallisti5** [comment]
Boop.

* https://github.com/Ultimaker/Ultimaker2Marlin/blob/master/Marlin/Configuration.h
* https://github.com/Ultimaker/Ultimaker2Marlin/blob/master/Marlin/Configuration_adv.h

There are other customization within that repo, but hopefully not too much in the business logic around config params.

**Pull request merged**
