### PR TITLE
Update configs for LumenPnP

### LINKED ISSUE #584: Update Marlin configuration with higher-resolution microstepping
Our present Marlin configuration uses a very low resolution microstepping setting. The community has tested increasing these to the maximum of `256` steps for the X & Y axis without any drawbacks which allows consistent sub-millimeter movement.

This requires an update to the Marlin configuration repository, so no action is needed in this repository.

### PR DESCRIPTION
**Pull request by theacodes**
### Description

* Renames the files from `Index/REV_03` to `Opulo/Lumen_REV3`, since the company & machine have been renamed for legal reasons.
* Changes microstepping resolution to `256` as per https://github.com/opulo-inc/lumenpnp/issues/584.

### Benefits

* Configuration file names now match the company and product nae.
* Higher microstepping resolution allows for more accurate calibration and placement.

### Related Issues

Closes https://github.com/opulo-inc/lumenpnp/issues/584

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Since you're using TMC2209s and have `INTERPOLATE` set to true in this config, microsteps are already interpolated to 256.

You'd probably achieve the same level precision if you double or quadruple your standard steps/mm & microsteps instead of potentially overloading the MCU with raw microstepping set to 256.

**Comment by theacodes** [comment]
The CPU isn't haven't any issue keeping up with our steps/s, since the Lumen is a relatively slow machine.

**Comment by thisiskeithb** [comment]
@theacodes: Just to confirm, this is the "LumenPnP" by "Opulo" with a motherboard named "REV3"? We need to rename code/tests upstream in the main Marlin repo and I want to make sure this is named properly.

Edit:

- This PR completes the rename upstream in Marlin: https://github.com/MarlinFirmware/Marlin/pull/24433
- This PR shortens the `MOTHERBOARD` define/drops "Lumen" since that is the machine the REV3 motherboard goes into and not part of the motherboard model: https://github.com/MarlinFirmware/Configurations/pull/769

**Comment by theacodes** [comment]
That's correct. Thank you

**Comment by thisiskeithb** [comment]
@theacodes Since you replied via email you probably didn't see my edit: https://github.com/MarlinFirmware/Configurations/pull/766#issuecomment-1171261641

**Comment by theacodes** [comment]
Got it. Yes, that's fine. It can be referred to as the "Lumen REV3" or just "REV3", we'll have a REV4 that's quite a bit different eventually.

**Pull request merged**
