### PR TITLE
official sv06 configuration

### PR DESCRIPTION
**Pull request by mrpond**
### Description

Configuration taken from Sovol3D's GitHub repository.
Disable #define SPEAKER relate to below issue.
* untested, at the time of commit I'm still waiting for SV06 📦 to delivery. 

### Benefits

Added SV06 configuration

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/26982

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for the contribution! Configurations need to be based on the current `import-2.1.x` development branch for acceptance. I went ahead and updated the configurations by hand. I might have missed something, so you should double check them and make sure they work properly with the `bugfix-2.1.x` branch, which will be the basis for the next release, 2.1.3. You might also want to enable and test some of the new features (like Input Shaping and provide default tuning values), which Sovol may not have tuned out of the box. Reviewers did note that other Sovol SV0x models had poor calibration out of the box, so we want to make sure we're doing a good job of fixing those up.

**Comment by mrpond** [comment]
Hi, I do use the config.ini to generate these.
[sv06.zip](https://github.com/user-attachments/files/16326516/sv06.zip)

Compile successfully on Marlin bugfix-2.1.x 
7f0d7e760b87bad296fee946b9afd2f6e3925f28

my platformio.ini
change config.ini into sv06.ini
```
[platformio]
src_dir      = Marlin
boards_dir   = buildroot/share/PlatformIO/boards
default_envs = GD32F103RET6_sovol_maple
include_dir  = Marlin
extra_configs =
    Marlin/sv06.ini

....


```

I do revert some of your change, 
e.g. PID_PARAMS_PER_HOTEND is not enable, else condition apply

ADVANCE_K { 0.04 } -> 0.04 the sanity check error when add { } 

PROBE_OFFSET_ZMIN/ ZMAX ifndef already -20 / 20

**Comment by thisiskeithb** [comment]
You've changed a bunch of spacing and removed config defines in https://github.com/MarlinFirmware/Configurations/pull/1083/commits/b8d2d2bf531ded9f25a6f6728231a1885cb3c7fb that should remain.

**Comment by mrpond** [comment]
> You've changed a bunch of spacing and removed config defines in [b8d2d2b](https://github.com/MarlinFirmware/Configurations/commit/b8d2d2bf531ded9f25a6f6728231a1885cb3c7fb) that should remain.

Hi, I didn't do these by hand. 
those are by marlin build script. check sv06.zip

some of define already done upstream, so I remove it

**Comment by thisiskeithb** [comment]
> Hi, I didn't do these by hand.
> those are by marlin build script.

Even so, the changes need to be reverted, so please revert them and push an update.

**Comment by mrpond** [comment]
> > Hi, I didn't do these by hand.
> > those are by marlin build script.
> 
> Even so, the changes need to be reverted, so please revert them and push an update.

done, I'm not sure if it correct. please check

**Comment by mrpond** [comment]
@thinkyhead I got real hardware now, configuration working

photo_2024-08-10_21-25-05
photo_2024-08-10_21-25-06
photo_2024-08-10_21-25-09
photo_2024-08-10_21-25-07

https://github.com/user-attachments/assets/a666416b-5a72-4272-8cf9-6a6aec51f3cd

**Comment by thinkyhead** [comment]
Thanks for all your work and testing! I reduced the motor current for homing by a small amount. It should not make a huge difference in homing behavior, but feel free to tune those currents a bit more and submit an update.

**Comment by mrpond** [comment]
> Thanks for all your work and testing! I reduced the motor current for homing by a small amount. It should not make a huge difference in homing behavior, but feel free to tune those currents a bit more and submit an update.

Tested, homing working fine.

**Pull request merged**
